query ArtifactById(
  $id: BigInt!
) {
  artifactById (id: $id){
    id
    name
    description
    artifactType: artifactTypeByArtifactTypeId {
      id
      name
    }
    patches: patchesByArtifactId {
      nodes {
        id
        number
        ddlUp
        ddlDown
        minor: minorByMinorId {
          id
          number
          name
          major: majorByMajorId {
            id
            name
            revision
          }
          release: releaseByReleaseId {
            id
            name
            number
          }
        }
      }
    }
  }
}
