query PatchById(
  $id: BigInt!
) {
  patchById (id: $id){
    id
    number
    ddlUp
    ddlDown
    artifact: artifactByArtifactId {
      id
      name
      artifactType: artifactTypeByArtifactTypeId {
        id
        name
      }
    }
    patchType: patchTypeByPatchTypeId {
      id
      name
    }
    devDeployment: devDeploymentByDevDeploymentId {
      id
      status
    }
    minor: minorByMinorId {
      id
      number
      name
      releaseId
      major: majorByMajorId {
        id
        name
        revision
      }
      release: releaseByReleaseId {
        id
        name
        number
      }
    }
  }
}
