query PdeProjectById(
  $id: BigInt!
) {
  pdeProjectById(id: $id) {
    id    
    name
    releases: releasesByProjectId(orderBy: NUMBER_ASC) {
      nodes {
        id
        name
        number
        status
        projectId
        minors: minorsByReleaseId(
          orderBy: NUMBER_ASC
        ) {
          nodes {
            id
            number
            name
            revision
            major: majorByMajorId {
              id
              name
              revision
            }
            patches: patchesByMinorId(
              orderBy: NUMBER_ASC
            ) {
              nodes {
                id
                number
                revision
                artifact: artifactByArtifactId {
                  id
                  name
                  schema: schemaBySchemaId {
                    id
                    name
                  }
                  artifactType: artifactTypeByArtifactTypeId {
                    id
                    name
                    properties
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  allArtifactTypes {
    nodes {
      id
      name
      properties
    }
  }

}