query ReleaseById(
  $id: BigInt!
) {
  release: releaseById(id: $id) {
    id
    name
    number
    minors: minorsByReleaseId(
      orderBy: NUMBER_ASC
    ) {
      nodes {
        id
        number
        name
        revision
        major: majorByMajorId {
          id
          revision
          name
        }
        patches: patchesByMinorId(
          orderBy: NUMBER_ASC
        ) {
          nodes {
            id
            number
            revision
            artifact: artifactByArtifactId {
              id
              name
              schema: schemaBySchemaId {
                id
                name
              }
              artifactType: artifactTypeByArtifactTypeId {
                id
                name
              }
            }
          }
        }
        gqlTests: testsByMinorId(filter: {
          type: {equalTo: GRAPH_QL}
        }) {
          nodes {
            id
            name
            ddl
            workingDdl
            type
          }
        }
        pgtTests: testsByMinorId(filter: {
          type: {equalTo: PG_TAP}
        }) {
          nodes {
            id
            name
            ddl
            workingDdl
            type
          }
        }
      }
    }
  }

  allArtifactTypes {
    nodes {
      id
      name
      children {
        nodes {
          id
          name
        }
      }
    }
  }

}